### ISSUE TITLE
TRADFRI bulb E27 CWS opal 600lm Error

### ISSUE THREAD

**Issue by MarcE85** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#106]
**Issue description**
Hey,

i get an error if i try to change the state of my IKEA TRADFRI Lamp.

**Additional information**
Zigbee2MQTT version: 1.3.0 Dev
Python version: 3.5.3
Domoticz version: latest dev
Plugin version: 0.0.18

**Logs**
Domoticz log:
2019-04-13 12:19:47.890 Error: (Zigbee2MQTT_livingroom) 'onMessage' failed 'KeyError'.
2019-04-13 12:19:47.890 Error: (Zigbee2MQTT_livingroom) ----> Line 193 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-04-13 12:19:47.890 Error: (Zigbee2MQTT_livingroom) ----> Line 106 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-04-13 12:19:47.890 Error: (Zigbee2MQTT_livingroom) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2019-04-13 12:19:47.891 Error: (Zigbee2MQTT_livingroom) ----> Line 166 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2019-04-13 12:19:47.891 Error: (Zigbee2MQTT_livingroom) ----> Line 21 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handleMqttMessage
2019-04-13 12:19:47.891 Error: (Zigbee2MQTT_livingroom) ----> Line 68 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function handle_message
2019-04-13 12:19:47.891 Error: (Zigbee2MQTT_livingroom) ----> Line 24 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function get_color_value
2019-04-13 12:19:48.547 Error: (Zigbee2MQTT_livingroom) 'onMessage' failed 'KeyError'.
2019-04-13 12:19:48.547 Error: (Zigbee2MQTT_livingroom) ----> Line 193 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-04-13 12:19:48.547 Error: (Zigbee2MQTT_livingroom) ----> Line 106 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-04-13 12:19:48.548 Error: (Zigbee2MQTT_livingroom) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2019-04-13 12:19:48.548 Error: (Zigbee2MQTT_livingroom) ----> Line 166 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2019-04-13 12:19:48.548 Error: (Zigbee2MQTT_livingroom) ----> Line 21 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handleMqttMessage
2019-04-13 12:19:48.548 Error: (Zigbee2MQTT_livingroom) ----> Line 68 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function handle_message
2019-04-13 12:19:48.548 Error: (Zigbee2MQTT_livingroom) ----> Line 24 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function get_color_value

MQTT Log:
2019-4-13 12:21:34 - debug: Received MQTT message on 'zigbee2mqtt/0xd0cf5efffe26bea1/set' with data '{"state": "On"}'
2019-4-13 12:21:34 - info: Zigbee publish to device '0xd0cf5efffe26bea1', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null
2019-4-13 12:21:34 - info: MQTT publish: topic 'zigbee2mqtt/0xd0cf5efffe26bea1', payload '{"state":"ON","linkquality":131,"brightness":254,"color_mode":2,"color":{"x":0.458,"y":0.41},"device":{"ieeeAddr":"0xd0cf5efffe26bea1","friendlyName":"0xd0cf5efffe26bea1","type":"Router","nwkAddr":47598,"manufId":4476,"manufName":"IKEA of Sweden","modelId":"TRADFRI bulb E27 CWS opal 600lm","hwVersion":1,"swBuildId":"unknown","dateCode":"unknown","status":"online"}}'
2019-4-13 12:21:35 - debug: Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"16387":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}}' of device 'TRADFRI bulb E27 CWS opal 600lm' (0xd0cf5efffe26bea1) of endpoint 1
2019-4-13 12:21:35 - info: MQTT publish: topic 'zigbee2mqtt/0xd0cf5efffe26bea1', payload '{"state":"ON","linkquality":131,"brightness":254,"color_mode":2,"color":{"x":0.458,"y":0.41},"device":{"ieeeAddr":"0xd0cf5efffe26bea1","friendlyName":"0xd0cf5efffe26bea1","type":"Router","nwkAddr":47598,"manufId":4476,"manufName":"IKEA of Sweden","modelId":"TRADFRI bulb E27 CWS opal 600lm","hwVersion":1,"swBuildId":"unknown","dateCode":"unknown","status":"online"}}'
2019-4-13 12:21:35 - debug: Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"65533":1}}' of device 'TRADFRI bulb E27 CWS opal 600lm' (0xd0cf5efffe26bea1) of endpoint 1

**Comment by MarcE85** [comment]
Fixed; Updatet Plugin and reloaded Domoticz

**Comment by rldn21** [comment]
Hi, im still having this issue running when i change the state of the e27 bulb. Ive downloaded the latest version of the zigbee2mqtt plugin, domoticz and python. Without success.....

**Comment by stas-demydiuk** [comment]
@rldn21 could you please provide your log

**Comment by rldn21** [comment]
Hi, thanks for your reply.

Here is the log of domoticz when switch on/off the E27 bulb:


2019-06-19 19:15:33.383 Error: (zigbee2mqtt) 'onMessage' failed 'KeyError'.
2019-06-19 19:15:33.383 Error: (zigbee2mqtt) ----> Line 193 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-06-19 19:15:33.383 Error: (zigbee2mqtt) ----> Line 106 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-06-19 19:15:33.383 Error: (zigbee2mqtt) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2019-06-19 19:15:33.383 Error: (zigbee2mqtt) ----> Line 166 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2019-06-19 19:15:33.383 Error: (zigbee2mqtt) ----> Line 21 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handleMqttMessage
2019-06-19 19:15:33.383 Error: (zigbee2mqtt) ----> Line 68 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function handle_message
2019-06-19 19:15:33.383 Error: (zigbee2mqtt) ----> Line 24 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function get_color_value


Hope you can help me. The lamp goes on or off, but the status in domoticz doesnt change. It stays On all the time…

**Comment by stas-demydiuk** [comment]
And could you please share mqtt messages produced by zigbee2mqtt when you switch device on/off

**Comment by rldn21** [comment]
zigbee2mqtt:debug 2019-6-19 22:08:21 Received MQTT message on 'zigbee2mqtt/hoeklamp/set' with data '{"state": "Off"}'
zigbee2mqtt:info 2019-6-19 22:08:21 Zigbee publish to device '0x90fd9ffffeedfd1f', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
zigbee2mqtt:info 2019-6-19 22:08:21 MQTT publish: topic 'zigbee2mqtt/hoeklamp', payload '{"state":"OFF","linkquality":13,"brightness":86,"color":{"x":0.458,"y":0.41},"color_mode":2}'
zigbee2mqtt:debug 2019-6-19 22:08:21 Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"16387":1,"onOff":0,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}}' of device 'TRADFRI bulb E27 CWS opal 600lm' (0x90fd9ffffeedfd1f) of endpoint 1
zigbee2mqtt:info 2019-6-19 22:08:21 MQTT publish: topic 'zigbee2mqtt/hoeklamp', payload '{"state":"OFF","linkquality":10,"brightness":86,"color":{"x":0.458,"y":0.41},"color_mode":2}'
zigbee2mqtt:debug 2019-6-19 22:08:21 Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"65533":1}}' of device 'TRADFRI bulb E27 CWS opal 600lm' (0x90fd9ffffeedfd1f) of endpoint 1

**Comment by stas-demydiuk** [comment]
@rldn21 I extracted your issue in separate ticket (#123)
