### ISSUE TITLE
updated to v.1.16.2 (zStack12 20190608), devices are visible but NO sensor updates ....

### ISSUE THREAD

**Issue by Eddie-BS** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#525]
**Issue description**
updated to v.1.16.2 (zStack12 20190608), devices are visible but NOT sensor updates ....

**Additional information**
Zigbee2MQTT version:
Python version: latest RPI
Domoticz version: 12741
Plugin version: 1.16.2

All devices are visible and the timestamps are updated ...

<img width="1194" alt="Screenshot 2020-12-20 at 15 05 01" src="https://user-images.githubusercontent.com/10174704/102715336-fbcdca80-42d4-11eb-8b3a-6a22600569e3.png">

the sensors are NOT updated since I updated the pluging this morning ....

<img width="1186" alt="Screenshot 2020-12-20 at 15 05 20" src="https://user-images.githubusercontent.com/10174704/102715340-025c4200-42d5-11eb-9a01-d4f7bfae0b9b.png">

**Logs**
root@domoticz:/opt/zigbee2mqtt/data/log/2020-12-20.14-50-03# cat log.txt 
info  2020-12-20 14:50:06: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-12-20.14-50-03' filename: log.txt
info  2020-12-20 14:50:07: Starting Zigbee2MQTT version 1.16.2 (commit #04c15f7)
info  2020-12-20 14:50:07: Starting zigbee-herdsman (0.13.37)
info  2020-12-20 14:50:11: zigbee-herdsman started
info  2020-12-20 14:50:11: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
info  2020-12-20 14:50:11: Currently 11 devices are joined:
info  2020-12-20 14:50:11: Ikea Led strip (0x588e81fffe60b97c): ICPSHC24-30EU-IL-1 - IKEA TRADFRI driver for wireless control (30 watt) (Router)
info  2020-12-20 14:50:11: Ikea Remote control (0x000d6ffffe490ab8): E1524/E1810 - IKEA TRADFRI remote control (EndDevice)
info  2020-12-20 14:50:11: MiJiaT1 zolder (0x00158d0003ce8b6f): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
info  2020-12-20 14:50:11: MiJiaT2 gangkast (0x00158d0003ce89d0): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
info  2020-12-20 14:50:11: MiJiaT3 keuken (0x00158d0003ce8b68): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
info  2020-12-20 14:50:11: AqaraT2 Schuur (0x00158d00054c588b): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
info  2020-12-20 14:50:11: AqaraT1 Badkamer (0x00158d0004ab61c7): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
info  2020-12-20 14:50:11: ZButton1 (0x00124b002228614a): SNZB-01 - SONOFF Wireless button (EndDevice)
info  2020-12-20 14:50:11: ZButton2 (0x00124b002228e4e6): SNZB-01 - SONOFF Wireless button (EndDevice)
info  2020-12-20 14:50:11: MiJiaL1 schouw (0x04cf8cdf3c78cfaf): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
info  2020-12-20 14:50:11: MiJiaL2 raam (0x04cf8cdf3c7cb564): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
warn  2020-12-20 14:50:11: `permit_join` set to  `true` in configuration.yaml.
warn  2020-12-20 14:50:11: Allowing new devices to join.
warn  2020-12-20 14:50:11: Set `permit_join` to `false` once you joined all devices.
info  2020-12-20 14:50:11: Zigbee: allowing new devices to join.
info  2020-12-20 14:50:11: Connecting to MQTT server at mqtt://localhost
info  2020-12-20 14:50:11: Connected to MQTT server
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/Ikea Led strip', payload '{"brightness":153,"linkquality":47,"state":"OFF","update_available":false}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/Ikea Remote control', payload '{"battery":34,"linkquality":44,"update_available":false}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/MiJiaT1 zolder', payload '{"battery":80,"humidity":62.05,"linkquality":55,"temperature":15.29,"voltage":2965}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/MiJiaT2 gangkast', payload '{"battery":100,"humidity":47.43,"linkquality":97,"temperature":21.63,"voltage":3005}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/MiJiaT3 keuken', payload '{"battery":91,"humidity":49.57,"temperature":19.66,"voltage":2985}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/AqaraT2 Schuur', payload '{"battery":91,"humidity":66.74,"pressure":1014,"temperature":14.28,"voltage":2985}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/AqaraT1 Badkamer', payload '{"battery":100,"humidity":56.88,"linkquality":44,"pressure":1014,"temperature":18.77,"voltage":3015}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/ZButton1', payload '{"battery":100,"linkquality":44,"voltage":3100}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/ZButton2', payload '{"battery":90.5,"linkquality":44,"voltage":2900}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/MiJiaL1 schouw', payload '{"battery":100,"illuminance":10414,"illuminance_lux":11,"linkquality":42,"voltage":3100}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/MiJiaL2 raam', payload '{"battery":100,"illuminance":20828,"illuminance_lux":121,"linkquality":42,"voltage":3100}'
info  2020-12-20 14:50:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[],"type":"groups"}'
info  2020-12-20 14:50:12: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"04c15f7","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.16.2"}'
info  2020-12-20 14:50:22: MQTT publish: topic 'zigbee2mqtt/AqaraT2 Schuur', payload '{"battery":91,"humidity":66.74,"linkquality":5,"pressure":1014,"temperature":13.2,"voltage":2985}'
info  2020-12-20 14:50:22: MQTT publish: topic 'zigbee2mqtt/AqaraT2 Schuur', payload '{"battery":91,"humidity":70.15,"linkquality":5,"pressure":1014,"temperature":13.2,"voltage":2985}'
info  2020-12-20 14:50:22: MQTT publish: topic 'zigbee2mqtt/AqaraT2 Schuur', payload '{"battery":91,"humidity":70.15,"linkquality":5,"pressure":1014,"temperature":13.2,"voltage":2985}'
info  2020-12-20 14:50:30: MQTT publish: topic 'zigbee2mqtt/MiJiaL2 raam', payload '{"battery":100,"illuminance":21904,"illuminance_lux":155,"linkquality":44,"voltage":3100}'
info  2020-12-20 14:50:45: MQTT publish: topic 'zigbee2mqtt/MiJiaL2 raam', payload '{"battery":100,"illuminance":22480,"illuminance_lux":177,"linkquality":44,"voltage":3100}'
info  2020-12-20 14:50:46: MQTT publish: topic 'zigbee2mqtt/MiJiaL1 schouw', payload '{"battery":100,"illuminance":11761,"illuminance_lux":15,"linkquality":44,"voltage":3100}'
info  2020-12-20 14:50:47: MQTT publish: topic 'zigbee2mqtt/MiJiaT2 gangkast', payload '{"battery":100,"humidity":47.43,"linkquality":102,"temperature":20.86,"voltage":3005}'
info  2020-12-20 14:50:47: MQTT publish: topic 'zigbee2mqtt/MiJiaT2 gangkast', payload '{"battery":100,"humidity":43.74,"linkquality":102,"temperature":20.86,"voltage":3005}'
info  2020-12-20 14:51:00: MQTT publish: topic 'zigbee2mqtt/MiJiaL2 raam', payload '{"battery":100,"illuminance":23054,"illuminance_lux":202,"linkquality":44,"voltage":3100}'
info  2020-12-20 14:51:01: MQTT publish: topic 'zigbee2mqtt/MiJiaL1 schouw', payload '{"battery":100,"illuminance":12305,"illuminance_lux":17,"linkquality":44,"voltage":3100}'

**Comment by faratou** [comment]
With zigbee2mqtt version 1.16.2 & plug-in v3.0
You need to add to the zigbee2mqtt configuration.yaml:

experimental:
  new_api: true

**Comment by Dylantje** [comment]
do you have a solution?

**Comment by stas-demydiuk** [comment]
Do you have any errors in Domotcz log?

**Comment by Dylantje** [comment]
i start form the beginning...
New router and new plugin so new start i thnik better..
Thnaks for the support..
And sorry i can get no log to you

**Comment by vakhramov** [comment]
Domoticz Version: 2020.2
Python 3.7.3
node --version v12.9.1
npm --version 6.10.2
v.1.17.0 (zStack12 20190608)

Not updated devices state, after change friendly_name, no errors in domoticz log. If you don't change friendly_name everything will be updated. In the Zigbee2MQTT logs, information about the status of devices is updated.

![Screenshot_20210104_183407](https://user-images.githubusercontent.com/11798409/103545910-acce8a80-4ebb-11eb-9740-5426efcbe707.png)

pi@domoticz:/opt/zigbee2mqtt/data/log $ cat 2021-01-04.18-08-11/log.txt 
info  2021-01-04 18:08:29: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-01-04.18-08-11' filename: log.txt
info  2021-01-04 18:08:32: Starting Zigbee2MQTT version 1.17.0 (commit #07cdc9d)
info  2021-01-04 18:08:32: Starting zigbee-herdsman (0.13.46)
info  2021-01-04 18:08:48: zigbee-herdsman started
info  2021-01-04 18:08:48: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
info  2021-01-04 18:08:48: Currently 1 devices are joined:
info  2021-01-04 18:08:49: Temp/Humidity kitchen (0x00158d000159f2d3): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
warn  2021-01-04 18:08:49: `permit_join` set to  `true` in configuration.yaml.
warn  2021-01-04 18:08:49: Allowing new devices to join.
warn  2021-01-04 18:08:49: Set `permit_join` to `false` once you joined all devices.
info  2021-01-04 18:08:49: Zigbee: allowing new devices to join.
info  2021-01-04 18:08:49: Connecting to MQTT server at mqtt://localhost
info  2021-01-04 18:08:53: Connected to MQTT server
---skip---
Jan 04 18:22:16 domoticz npm[11592]: Zigbee2MQTT:info  2021-01-04 18:22:16: MQTT publish: topic 'zigbee2mqtt/Temp/Humidity kitchen', payload '{"battery":86,"humidity":67.2,"linkquality":102,"temperature":26.48,"voltage":2975}'
Jan 04 18:22:23 domoticz npm[11592]: Zigbee2MQTT:info  2021-01-04 18:22:23: MQTT publish: topic 'zigbee2mqtt/Temp/Humidity kitchen', payload '{"battery":86,"humidity":67.2,"linkquality":105,"temperature":26.61,"voltage":2975}'


pi@domoticz:/opt/zigbee2mqtt/data $ cat configuration.yaml 
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: null
  disable_led: true
experimental:
  new_api: true

**Comment by dheuts90** [comment]
Same problem here after updating.
Domoticz Version: 2020.2

Domoticz log:
2021-01-04 17:04:08.244 Error: (Zigbee Oud) 0x60a423fffeab59f8: device exposes not found
2021-01-04 17:04:08.245 Error: (Zigbee Oud) 'onMessage' failed 'TypeError':''NoneType' object is not subscriptable'.
2021-01-04 17:04:08.245 Error: (Zigbee Oud) ----> Line 279 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-01-04 17:04:08.245 Error: (Zigbee Oud) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-01-04 17:04:08.245 Error: (Zigbee Oud) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2021-01-04 17:04:08.245 Error: (Zigbee Oud) ----> Line 153 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2021-01-04 17:04:08.245 Error: (Zigbee Oud) ----> Line 24 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function set_devices

**Comment by leonhondje** [comment]
I've an isue with new devices, the devices are nog shown.
![image](https://user-images.githubusercontent.com/14952281/103572409-cc21e380-4ecc-11eb-9254-8b48f7ad3403.png)
In the log file I get the following error:  0x00158d0001de79af: device exposes not found
![image](https://user-images.githubusercontent.com/14952281/103572458-e52a9480-4ecc-11eb-9a61-679b874dfc75.png)

I have enabled the:
experimental:
new_api: true

**Comment by stas-demydiuk** [comment]
Please upgrade zigbee2mqtt to the latest version, the issue should be resolved

**Comment by Eddie-BS** [comment]
Hi, I did update to 1.17 as stated in
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/530
but still the same problem.

Sensors are not updated ...

I did a rollback to my previous plugin and now sensors are working again.

**Comment by stas-demydiuk** [comment]
#530 is now resolved, could you please check again

**Comment by Eddie-BS** [comment]
Hi,
still not working for all devices ...
here  is what I did : 
- removed zigbee2mqtt from hardware list
  this removed all devices and sensors
- removed the plugin/zigbee2mqtt directory
- did git clone https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt
- restarted domoticz
- added new hardware zigbee2mqtt
- all devices appeared and a lot of sensors ...
- most sensors do NOT update ...
- sensors that DO update   
<img width="1168" alt="Screenshot 2021-01-28 at 13 36 48" src="https://user-images.githubusercontent.com/10174704/106139594-ecf8f400-616d-11eb-8241-59335213bfc9.png">

<img width="1171" alt="Screenshot 2021-01-28 at 13 33 26" src="https://user-images.githubusercontent.com/10174704/106139220-75c36000-616d-11eb-9d1e-b54e086a7a81.png">

- sensors the DO NOT update
<img width="1173" alt="Screenshot 2021-01-28 at 13 34 52" src="https://user-images.githubusercontent.com/10174704/106139436-b8853800-616d-11eb-8126-f04dd6a444b9.png">

<img width="1168" alt="Screenshot 2021-01-28 at 13 35 13" src="https://user-images.githubusercontent.com/10174704/106139459-c044dc80-616d-11eb-9b2f-be6a6746aa08.png">

- not working also
<img width="1167" alt="Screenshot 2021-01-28 at 13 38 54" src="https://user-images.githubusercontent.com/10174704/106139825-377a7080-616e-11eb-90bc-fe600309a488.png">

<img width="1171" alt="Screenshot 2021-01-28 at 13 39 03" src="https://user-images.githubusercontent.com/10174704/106139839-3ba68e00-616e-11eb-8401-eed9f9ec2351.png">

<img width="1172" alt="Screenshot 2021-01-28 at 13 39 56" src="https://user-images.githubusercontent.com/10174704/106139968-6f81b380-616e-11eb-89d6-54f1fb8decb3.png">

<img width="1174" alt="Screenshot 2021-01-28 at 13 40 08" src="https://user-images.githubusercontent.com/10174704/106139978-73153a80-616e-11eb-95b1-578a5a940dbb.png">

**Comment by Eddie-BS** [comment]
Sorry to correct this.
NONE of the sensors are updating, ONLY the IKEA Led Strip and Remote values are parsed ...

**Comment by Eddie-BS** [comment]
some logging

zigbee2mqtt log
```
info  2021-01-28 22:12:08: MQTT publish: topic 'zigbee2mqtt/Repeater1', payload '{"linkquality":123}'
info  2021-01-28 22:12:26: MQTT publish: topic 'zigbee2mqtt/ZButton2 slaapkamer', payload '{"battery":80,"linkquality":107,"voltage":2900}'
```

domoticz log
```
2021-01-28 22:12:08.303  Python Plugin System: (Zigbee2MQTT) Received 180 bytes of data
2021-01-28 22:12:08.303  Python Plugin System: (Zigbee2MQTT)     64 67 65 2f 6c 6f 67 67 69 6e 67 7b 22 6c 65 76 65 6c 22 3a     dge/logging{"level":
2021-01-28 22:12:08.303  Python Plugin System: (Zigbee2MQTT)     22 69 6e 66 6f 22 2c 22 6d 65 73 73 61 67 65 22 3a 22 4d 51     "info","message":"MQ
2021-01-28 22:12:08.303  Python Plugin System: (Zigbee2MQTT)     54 54 20 70 75 62 6c 69 73 68 3a 20 74 6f 70 69 63 20 27 7a     TT.publish:.topic.'z
2021-01-28 22:12:08.304  Python Plugin System: (Zigbee2MQTT)     69 67 62 65 65 32 6d 71 74 74 2f 52 65 70 65 61 74 65 72 31     igbee2mqtt/Repeater1
2021-01-28 22:12:08.304  Python Plugin System: (Zigbee2MQTT)     27 2c 20 70 61 79 6c 6f 61 64 20 27 7b 5c 22 6c 69 6e 6b 71     ',.payload.'{\"linkq
2021-01-28 22:12:08.304  Python Plugin System: (Zigbee2MQTT)     75 61 6c 69 74 79 5c 22 3a 31 32 33 7d 27 22 7d 30 2a 00 15     uality\":123}'"}0*..
2021-01-28 22:12:08.304  Python Plugin System: (Zigbee2MQTT)     7a 69 67 62 65 65 32 6d 71 74 74 2f 52 65 70 65 61 74 65 72     zigbee2mqtt/Repeater
2021-01-28 22:12:08.304  Python Plugin System: (Zigbee2MQTT)     31 7b 22 6c 69 6e 6b 71 75 61 6c 69 74 79 22 3a 31 32 33 7d     1{"linkquality":123}
2021-01-28 22:12:11.121  Python Plugin System: (Zigbee2MQTT) MqttClient::ping
2021-01-28 22:12:11.212  Python Plugin System: (Zigbee2MQTT) Sending 2 bytes of data
2021-01-28 22:12:11.213  Python Plugin System: (Zigbee2MQTT) Received 2 bytes of data
2021-01-28 22:12:21.077  Python Plugin System: (Zigbee2MQTT) MqttClient::ping
2021-01-28 22:12:21.078  Python Plugin System: (Zigbee2MQTT) Sending 2 bytes of data
2021-01-28 22:12:21.133  Python Plugin System: (Zigbee2MQTT) Received 2 bytes of data
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT) Received 178 bytes of data
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     64 67 65 2f 6c 6f 67 67 69 6e 67 7b 22 6c 65 76 65 6c 22 3a     dge/logging{"level":
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     22 69 6e 66 6f 22 2c 22 6d 65 73 73 61 67 65 22 3a 22 4d 51     "info","message":"MQ
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     54 54 20 70 75 62 6c 69 73 68 3a 20 74 6f 70 69 63 20 27 7a     TT.publish:.topic.'z
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     69 67 62 65 65 32 6d 71 74 74 2f 5a 42 75 74 74 6f 6e 32 20     igbee2mqtt/ZButton2.
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     73 6c 61 61 70 6b 61 6d 65 72 27 2c 20 70 61 79 6c 6f 61 64     slaapkamer',.payload
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     20 27 7b 5c 22 62 61 74 74 65 72 79 5c 22 3a 38 30 2c 5c 22     .'{\"battery\":80,\"
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     6c 69 6e 6b 71 75 61 6c 69 74 79 5c 22 3a 31 30 37 2c 5c 22     linkquality\":107,\"
2021-01-28 22:12:26.484  Python Plugin System: (Zigbee2MQTT)     76 6f 6c 74 61 67 65 5c 22 3a 32 39 30 30 7d 27 22 7d .. ..     voltage\":2900}'"}
2021-01-28 22:12:26.485  Python Plugin System: (Zigbee2MQTT) Received 82 bytes of data
2021-01-28 22:12:26.485  Python Plugin System: (Zigbee2MQTT)     30 50 00 1f 7a 69 67 62 65 65 32 6d 71 74 74 2f 5a 42 75 74     0P..zigbee2mqtt/ZBut
2021-01-28 22:12:26.485  Python Plugin System: (Zigbee2MQTT)     74 6f 6e 32 20 73 6c 61 61 70 6b 61 6d 65 72 7b 22 62 61 74     ton2.slaapkamer{"bat
2021-01-28 22:12:26.485  Python Plugin System: (Zigbee2MQTT)     74 65 72 79 22 3a 38 30 2c 22 6c 69 6e 6b 71 75 61 6c 69 74     tery":80,"linkqualit
2021-01-28 22:12:26.485  Python Plugin System: (Zigbee2MQTT)     79 22 3a 31 30 37 2c 22 76 6f 6c 74 61 67 65 22 3a 32 39 30     y":107,"voltage":290
2021-01-28 22:12:26.485  Python Plugin System: (Zigbee2MQTT)     30 7d .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     0}
2021-01-28 22:12:31.106  Python Plugin System: (Zigbee2MQTT) MqttClient::ping
2021-01-28 22:12:31.107  Python Plugin System: (Zigbee2MQTT) Sending 2 bytes of data
2021-01-28 22:12:31.158  Python Plugin System: (Zigbee2MQTT) Received 2 bytes of data
2021-01-28 22:12:41.123  Python Plugin System: (Zigbee2MQTT) MqttClient::ping

```

looks like not the entire message is getting into domoticz ?

**Comment by stas-demydiuk** [comment]
```
info  2021-01-28 22:12:08: MQTT publish: topic 'zigbee2mqtt/Repeater1', payload '{"linkquality":123}'
info  2021-01-28 22:12:26: MQTT publish: topic 'zigbee2mqtt/ZButton2 slaapkamer', payload '{"battery":80,"linkquality":107,"voltage":2900}'
```

There is no useful payload in these messages, only `linkquality` and `battery` status updates, which should still update appropriate devices (`_signal` and `_btperc`  if you have such)

**Comment by Eddie-BS** [comment]
Here you go
The device repeater1 is updated
<img width="1172" alt="Screenshot 2021-01-29 at 08 01 31" src="https://user-images.githubusercontent.com/10174704/106242746-7230e700-6208-11eb-92ef-3ffe84b8c1ad.png">

the sensor _signal is created but not updated
<img width="1170" alt="Screenshot 2021-01-29 at 08 01 44" src="https://user-images.githubusercontent.com/10174704/106242774-82e15d00-6208-11eb-9cc6-eb349eb527e2.png">

The device ZButton2 is updated
<img width="1173" alt="Screenshot 2021-01-29 at 08 02 11" src="https://user-images.githubusercontent.com/10174704/106242827-9a204a80-6208-11eb-958b-7a452e0b2e85.png">

The sensors are created but not updated
<img width="1174" alt="Screenshot 2021-01-29 at 08 02 47" src="https://user-images.githubusercontent.com/10174704/106242853-a4424900-6208-11eb-9f8e-208f5b935637.png">

**Comment by Eddie-BS** [comment]
device Ikea remote control is updated
<img width="1170" alt="Screenshot 2021-02-02 at 14 39 21" src="https://user-images.githubusercontent.com/10174704/106608300-848e8600-6564-11eb-8de8-3e193029f34c.png">

sensors are UPDATED too (don't know why the battery voltage is not ...)
<img width="1170" alt="Screenshot 2021-02-02 at 14 39 39" src="https://user-images.githubusercontent.com/10174704/106608455-b69fe800-6564-11eb-802d-e2ce8cfe6984.png">

**Comment by heggink** [comment]
It’s not uncommon for IKEA to not send battery data until you give it a reconfigure command through the z2m page (or via mosquito_pub). I had to do that for all my remotes before it would report battery..

**Comment by Eddie-BS** [comment]
> It’s not uncommon for IKEA to not send battery data until you give it a reconfigure command through the z2m page (or via mosquito_pub). I had to do that for all my remotes before it would report battery..

Hmm, nice to know it is possible, any link to how to do that ?

My previous comment was actually to indicate that NONE of my zigbee device sensors are working with the 3.0 plugin except the Ikea led strip and the Ikea remote ...

**Comment by heggink** [comment]
Ah, sorry. Reconfigure is really simple: enable the z2m webpage in the z2m config (if you haven’t already, add a section “frontend:” and a line
 “ port: 8888”). Click on the middle of the 2 grey icons at the right. You do need to wake up the device before you do that.

**Comment by Eddie-BS** [comment]
Tnx for that, did not find that before ...
I can manage Z2M thru the frontend now.

I noticed Z2M was updated to 1.17.1, update went smooth.

Reconfigure of the Ikea remote did NOT work, still no battery voltage

**Comment by heggink** [comment]
That may take some time.


Herman Eggink

________________________________

**Comment by Eddie-BS** [comment]
The good news is : The UPDATE of Z2M to 1.17.1 seemed to have solved my problems. My devices are updating now.
Ikea Remote battery voltage still not availiable
trying to bind a device to an other router in my network is not successfull yet (with Z2M frontend)

**Comment by Eddie-BS** [comment]
All is working fine now with Z2M 1.17.1 and the latest plugin.
