### ISSUE TITLE
diyruz-diyruz_flower

### ISSUE THREAD

**Issue by Bartekn86** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#588]
https://www.zigbee2mqtt.io/devices/DIYRuZ_Flower.html

do not show illuminance

thank you

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by Bartekn86** [comment]
Hi, Thank you for your help
Could you take a look at the screenshot? it seemed to me that only luxes are missing, but the sensor gives more data, e.g. soil moisture

Would there be a possibility to add that too?
![Bez tytułu](https://user-images.githubusercontent.com/69695376/112582712-16916d00-8df7-11eb-9de4-075b8d2b8799.png)

Thank you

**Comment by stas-demydiuk** [comment]
Done

**Comment by Bartekn86** [comment]
Thanks for such a quick response, I'm afraid that something is still wrong, it does not show soil moisture. Could you have a look once more please ?
![Bez tytułu](https://user-images.githubusercontent.com/69695376/112595364-9bd24d00-8e0a-11eb-93d7-5d6b6d088685.png)

**Comment by stas-demydiuk** [comment]
Do you have any issues in Domoticz log?

**Comment by Bartekn86** [comment]
No, only with geiger meter but this is another issiue
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/583

**Comment by Bartekn86** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/69695376/112596246-d8eb0f00-8e0b-11eb-982a-7581f1148d1b.png)
looks like duplicate temperatures instead of moisture

**Comment by stas-demydiuk** [comment]
According to the doc this device has 3 different temperature sensors https://www.zigbee2mqtt.io/devices/DIYRuZ_Flower.html, so that is correct.

That's strange, "soil_moisture" sensor should be created as well. Could you please check that you have not reached the Domoticz devices limit #325

**Comment by Bartekn86** [comment]
:(  you are right
What can we do with it ?
![Bez tytułu](https://user-images.githubusercontent.com/69695376/112597281-3a5fad80-8e0d-11eb-8dec-c86e44f23e94.png)

**Comment by stas-demydiuk** [comment]
Probably this feature could help #594

**Comment by Bartekn86** [comment]
Hi Stas. ds and bme sensors are showing the same values, there only two temperature sensors, not three
After blocking some devices there are no soill moisture 

Could you look into the code in meantime ?

Thank you

**Comment by 19leva89** [comment]
Сan you help?
![err](https://user-images.githubusercontent.com/71250243/116674804-c4230d80-a9ad-11eb-8265-5df1cfc3b668.jpg)

**Comment by stas-demydiuk** [comment]
Could you please create [feature tickets](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?assignees=&labels=new+feature&template=new-device-feature-support.md&title=%60feature_name%60+feature+support) for each feature that is still required

**Comment by Bartekn86** [comment]
i would like to do it, but i do not know how, i see the examples, but its to complicated to me. would there be a big problem if i asked you for it? the same problem with geiger counter :(
sorry and thank you,

**Comment by Bartekn86** [comment]
flower sensor seems to work properly, only geiger counter not
thank you

**Comment by Bartekn86** [comment]
wrong info last time, 
After update flower sensor fw to current seems no work again :(

**Comment by Bartekn86** [comment]
2021-09-12 13:15:24.267 Error: mqtt: (mqtt) geiger: can not process numeric item "radioactive_events_per_minute"
2021-09-12 13:15:24.267 Error: mqtt: (mqtt) geiger: can not process numeric item "radiation_dose_per_hour"
2021-09-12 13:15:24.267 Error: mqtt: (mqtt) geiger: can not process binary item "led_feedback"
2021-09-12 13:15:24.267 Error: mqtt: (mqtt) geiger: can not process binary item "buzzer_feedback"
2021-09-12 13:15:24.267 Error: mqtt: (mqtt) geiger: can not process numeric item "alert_threshold"
2021-09-12 13:15:24.267 Error: mqtt: (mqtt) geiger: can not process numeric item "sensors_count"
2021-09-12 13:15:24.267 Error: mqtt: (mqtt) geiger: can not process numeric item "sensitivity"
2021-09-12 13:15:55.647 Error: mqtt: (mqtt) geiger: can not process numeric item "radioactive_events_per_minute"
2021-09-12 13:15:55.647 Error: mqtt: (mqtt) geiger: can not process numeric item "radiation_dose_per_hour"
2021-09-12 13:15:55.647 Error: mqtt: (mqtt) geiger: can not process binary item "led_feedback"
2021-09-12 13:15:55.648 Error: mqtt: (mqtt) geiger: can not process binary item "buzzer_feedback"
2021-09-12 13:15:55.648 Error: mqtt: (mqtt) geiger: can not process numeric item "alert_threshold"
2021-09-12 13:15:55.648 Error: mqtt: (mqtt) geiger: can not process numeric item "sensors_count"
2021-09-12 13:15:55.648 Error: mqtt: (mqtt) geiger: can not process numeric item "sensitivity" 

Sorry Stas, i dont know how to create ticket, its a bit hard to me.
